name: back_to_monke
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_ipfs: ^0.0.2
  dio: ^4.0.6
  image_picker_web: ^2.1.1
  universal_io: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  glassmorphism_ui: ^0.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay-Bold.ttf
        - asset: assets/fonts/SFUIDisplay-Regular.otf
        - asset: assets/fonts/SFUIDisplay-Heavy.otf